study:
    title: Personality and Coping
    label: Neuroticism
    answer_types:
        -
            label: frequency
            description: Frequency scale
            choices:
                -
                    value: zero
                    text: none
                    order: 1
                -
                    value: 1-2
                    text: 1 to 2 times
                    order: 2
                -
                    value: 3-5
                    text: 3 to 5 times
                    order: 3
                -
                    value: 5+
                    text: over 5 times
                    order: 4
        -
            label: pos_accuracy
            description: Accuracy scale
            choices:
                -
                    value: 1
                    text: 1. very inaccurate
                    order: 1
                -
                    value: 2
                    text: 2. moderately inaccurate
                    order: 2
                -
                    value: 3
                    text: 3. neither inaccurate or accurate
                    order: 3
                -
                    value: 4
                    text: 4. moderately accurate
                    order: 4
                -
                    value: 5
                    text: 5. very accurate
                    order: 5
        -
            label: neg_accuracy
            description: Accuracy scale
            choices:
                -
                    value: 5
                    text: 1. very inaccurate
                    order: 1
                -
                    value: 4
                    text: 2. moderately inaccurate
                    order: 2
                -
                    value: 3
                    text: 3. neither inaccurate or accurate
                    order: 3
                -
                    value: 2
                    text: 4. moderately accurate
                    order: 4
                -
                    value: 1
                    text: 5. very accurate
                    order: 5
        -
            label: scale
            description: From 1 to 5, 1 being not at all
            choices:
                -
                    value: 1
                    text: not at all
                    order: 1
                -
                    value: 2
                    text: 2
                    order: 2
                -
                    value: 3
                    text: 3
                    order: 3
                -
                    value: 4
                    text: 4
                    order: 4
                -
                    value: 5
                    text: extremely
                    order: 5
        -
            label: strategies
            description: used coping strategies
            allow_multiple: true
            choices:
                -
                    value: sarcasm
                    text: sarcasm
                    order: 1
                -
                    value: humor
                    text: humor
                    order: 2
                -
                    value: distract
                    text: distractions
                    order: 3
                -
                    value: reappraisal
                    text: changing the way you think about something to make you feel better
                    order: 4
                -
                    value: self laugh
                    text: laughing at yourself
                    order: 5
                -
                    value: others laugh
                    text: laughing at others
                    order: 6
                -
                    value: venting
                    text: venting your feelings to someone else
                    order: 7
                -
                    value: suppression
                    text: putting something out of your mind to feel better and not think of it
                    order: 8
        -
            label: age
            description: Age
            regular_expresssion: \d+
        -
            label: sex
            description: Sex choice
            choices:
                -
                    value: Male
                    text: Male
                    order: 1
                -
                    value: Female
                    text: Female
                    order: 2
                -
                    value: DNA
                    text: Choose not to answer
                    order: 3
        -
            label: race
            description: Ethnicity choice
            choices:
                -
                    value: Hispanic or Latino
                    text: Hispanic or Latino
                    order: 1
                -
                    value: Black or African American
                    text: Black or African American
                    order: 2
                -
                    value: Native American or American Indian
                    text: Native American or American Indian
                    order: 3
                -
                    value: White
                    text: White
                    order: 4
                -
                    value: Asian or Pacific Islander
                    text: Asian or Pacific Islander
                    order: 5
                -
                    value: Other
                    text: Other
                    order: 6
    blocks:
        -
              label: sarcasm
              questions:
                  -
                      label: sarcasm_use_frequency
                      text: How many times did you use sarcasm today?
                      answer_type_label: frequency
        -
              label: stress
              questions:
                  -
                      label: daily_stress_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, how stressed did you feel today?
                      answer_type_label: scale
        -
              label: coping_strategies
              questions:
                  -
                      label: coping_mechanisms
                      text: Which of the following did you use today?
                      answer_type_label: strategies
                  -
                      label: daily_social_support
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, how socially supported did you feel today?
                      answer_type_label: scale
        -
              label: neurotic_tendencies
              questions:
                  -
                      label: daily_nervous_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt nervous today.
                      answer_type_label: scale
                  -
                      label: daily_proud_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt proud today?
                      answer_type_label: scale
                  -
                      label: daily_strong_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt strong today?
                      answer_type_label: scale
                  -
                      label: daily_upset_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt upset today.
                      answer_type_label: scale
                  -
                      label: daily_guilty_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt guilty today?
                      answer_type_label: scale
                  -
                      label: daily_angry_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt angry today?
                      answer_type_label: scale
                  -
                      label: daily_excited_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt excited today.
                      answer_type_label: scale
                  -
                      label: daily_inspired_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt inspired today?
                      answer_type_label: scale
                  -
                      label: daily_irritable_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt irritable today?
                      answer_type_label: scale
                  -
                      label: daily_determined_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt determined today?
                      answer_type_label: scale
                  -
                      label: daily_sad_scale
                      text: On a scale of 1 to 5, 1 being not at all, 5 being extremely, indicate to what extent you have felt sad today?
                      answer_type_label: scale
        -
              label: initial_neurotic
              questions:
                  -
                      label: initial_pos_relaxed
                      text: How accurate is this statement, "I am relaxed most of the time."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_blue
                      text: How accurate is this statement, "I seldom feel blue."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_bothered
                      text: How accurate is this statement, "I am not easily bothered by things."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_irritated
                      text: How accurate is this statement, "I rarely get irritated."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_mad
                      text: How accurate is this statement, "I seldom get mad."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_neg_stress
                      text: How accurate is this statement, "I get stressed out easily."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_worry
                      text: How accurate is this statement, "I worry about things."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_disturbed
                      text: How accurate is this statement, "I am easily disturbed."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_upset
                      text: How accurate is this statement, "I get upset easily."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_change
                      text: How accurate is this statement, "I change my mood a lot."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_mood
                      text: How accurate is this statement, "I have frequent mood swings."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_irritated
                      text: How accurate is this statement, "I get irritated easily."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_blue
                      text: How accurate is this statement, "I often feel blue."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_angry
                      text: How accurate is this statement, "I get angry easily."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_panic
                      text: How accurate is this statement, "I panic easily."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_threatened
                      text: How accurate is this statement, "I feel threatened easily."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_overwhelmed
                      text: How accurate is this statement, "I get overwhelmed by emotions."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_offense
                      text: How accurate is this statement, "I take offense easily."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_caught
                      text: How accurate is this statement, "I get caught up in my problems."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_grumble
                      text: How accurate is this statement, "I grumble about things."?
                      answer_type_label: neg_accuracy
        -
              label: initial_openess
              questions:
                  -
                      label: initial_pos_vocab
                      text: How accurate is this statement, "I have a rich vocabulary."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_excellent
                      text: How accurate is this statement, "I have excellent ideas."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_understand
                      text: How accurate is this statement, "I am quick to understand things."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_difficult
                      text: How accurate is this statement, "I use difficult words."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_reflect
                      text: How accurate is this statement, "I spend time reflecting on things."?
                      answer_type_label: pos_accuracy  
                  -
                      label: initial_pos_full
                      text: How accurate is this statement, "I am full of ideas."?
                      answer_type_label: pos_accuracy  
                  -
                      label: initial_pos_higher
                      text: How accurate is this statement, "I carry the conversation to a higher level."?
                      answer_type_label: pos_accuracy   
                  -
                      label: initial_pos_catch
                      text: How accurate is this statement, "I catch on to things quickly."?
                      answer_type_label: pos_accuracy 
                  -
                      label: initial_pos_handle
                      text: How accurate is this statement, "I can handle a lot of information."?
                      answer_type_label: pos_accuracy           
                  -
                      label: initial_pos_new
                      text: How accurate is this statement, "I love to think up new ways of doing things."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_read
                      text: How accurate is this statement, "I love to read challenging material."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_pos_many
                      text: How accurate is this statement, "I am good at many things."?
                      answer_type_label: pos_accuracy
                  -
                      label: initial_neg_abstract
                      text: How accurate is this statement, "I have difficulty understanding abstract ideas."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_interest
                      text: How accurate is this statement, "I am not interested in abstract ideas."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_imagination
                      text: How accurate is this statement, "I do not have a good imagination."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_complex
                      text: How accurate is this statement, "I try to avoid complex people."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_imagine
                      text: How accurate is this statement, "I have difficulty imagining things."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_read
                      text: How accurate is this statement, "I avoid difficult reading material."?
                      answer_type_label: neg_accuracy
                  -
                      label: initial_neg_probe
                      text: How accurate is this statement, "I will not probe deeply into a subject."?
                      answer_type_label: neg_accuracy
        -
              label: demographics
              questions:
                  -
                      label: sex
                      text: What is your sex?
                      answer_type_label: sex
                  -
                      label: age
                      text: What is your age?
                      answer_type_label: age
                  -
                      label: race
                      text: What is your ethnicity?
                      answer_type_label: race
    questionnaires:
      -
          label: sarcasm_daily
          blocks:
                - sarcasm
                - stress
                - coping_strategies
                - neurotic_tendencies
      -
        label: initial
        blocks:
              - initial_neurotic
              - initial_openess
              - demographics
    schedule_template:
        entries:
            -
                time_offset_hours: 0
                questionnaire_label: initial
            -
                time_offset_hours: 2
                questionnaire_label: sarcasm_daily
            -
                time_offset_hours: 24
                questionnaire_label: sarcasm_daily
            -
                time_offset_hours: 48
                questionnaire_label: sarcasm_daily
            -
                time_offset_hours: 72
                questionnaire_label: sarcasm_daily
            
