study: Neuroticism and Coping
    title: Personality and Coping
    label: Neuroticism
    answer_types:
        -
            label: frequency
            description: Frequency scale
            choices:
                -
                    value: zero
                    text: none
                    order: 1
                -
                    value: 1-2
                    text: 1 to 2 times
                    order: 2
                -
                    value: 3-5
                    text: 3 to 5 times
                    order: 3
                -
                    value: 5+
                    text: over 5 times
                    order: 4
        -
            label: accuracy
            description: Accuracy scale
            choices:
                -
                    value: 1
                    text: very inaccurate
                    order: 1
                -
                    value: 2
                    text: moderately inaccurate
                    order: 2
                -
                    value: 3
                    text: neither inaccurate or accurate
                    order: 3
                -
                    value: 4
                    text: moderately accurate
                    order: 4
                -
                    value: 5
                    text: very accurate
                    order: 5
        -
            label: scale
            description: From 1 to 10, 1 being not at all
            choices:
                -
                    value: 1
                    text: not at all
                    order: 1
                -
                    value: 2
                    text: 2
                    order: 2
                -
                    value: 3
                    text: 3
                    order: 3
                -
                    value: 4
                    text: 4
                    order: 4
                -
                    value: 5
                    text: 5
                    order: 5
                -
                    value: 6
                    text: 6
                    order: 6
                -
                    value: 7
                    text: 7
                    order: 7
                -
                    value: 8
                    text: 8
                    order: 8
                -
                    value: 9
                    text: 9
                    order: 9
                -
                    value: 10
                    text: extremely
                    order: 10
        -
            label: strategies
            description: used coping strategies
            choices:
                -
                    value: sarcasm
                    text: sarcasm
                    order: 1
                -
                    value: humor
                    text: humor
                    order: 2
                -
                    value: distractions
                    text: distract
                    order: 3
                -
                    value: reappraisal
                    text: reappraisal
                    order: 4
                -
                    value: laughing at yourself
                    text: self laugh
                    order: 5
                -
                    value: laughing at others
                    text: others laugh
                    order: 6
    blocks:
        -
              label: sarcasm
              questions:
                  -
                      label: sarcasm_use_frequency
                      text: How many times did you use sarcasm today?
                      answer_type_label: frequency
        -
              label: stress
              questions:
                  -
                      label: daily_stress_scale
                      text: On a scale of 1 to 10, 1 being not at all, 10 being extremely, how stressed did you feel today?
                      answer_type_label: scale
        -
              label: coping_strategies
              questions:
                  -
                      label: coping_mechanisms
                      text: Which of the following did you use today?
                      answer_type_label: strategies
                  -
                      label: daily_social_support
                      text: On a scale of 1 to 10, 1 being not at all, 10 being extremely, how socially supported did you feel today?
                      answer_type_label: scale
                  -
                      label: overall_social_support
                      text: On a scale of 1 to 10, 1 being not at all, 10 being extremely, how socially supported do you feel overall, not just today?
                      answer_type_label: scale
        -
              label: neurotic_tendencies
              questions:
                  -
                      label: daily_anger_scale
                      text: On a scale of 1 to 10, 1 being not at all, 10 being extremely, how angry did you feel today?
                      answer_type_label: scale
                  -
                      label: daily_sad_scale
                      text: On a scale of 1 to 10, 1 being not at all, 10 being extremely, how sad did you feel today?
                      answer_type_label: scale
                  -
                      label: daily_jealous_scale
                      text: On a scale of 1 to 10, 1 being not at all, 10 being extremely, how jealous did you feel today?
                      answer_type_label: scale
        -
              label: initial_neurotic
              questions:
                  -
                      label: initial_relaxed
                      text: How accurate is this statement: "I am relaxed most of the time."?
                      answer_type_label: accuracy
                  -
                      label: initial_self_like
                      text: How accurate is this statement: "I dislike myself."?
                      answer_type_label: accuracy
                  -
                      label: initial_worry
                      text: How accurate is this statement: "I worry about things."?
                      answer_type_label: accuracy
                  -
                      label: initial_panic
                      text: How accurate is this statement: "I panic easily."?
                      answer_type_label: accuracy
                  -
                      label: initial_self_pleased
                      text: How accurate is this statement: "I am very pleased with myself."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_irritated
                      text: How accurate is this statement: "I rarely get irritated."?
                      answer_type_label: accuracy
                  -
                      label: initial_stressed
                      text: How accurate is this statement: "I am stressed out easily."?
                      answer_type_label: accuracy
                  -
                      label: initial_sad
                      text: How accurate is this statement: "I am often down in the dumps."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_mad
                      text: How accurate is this statement: "I seldom get mad."?
                      answer_type_label: accuracy
                  -
                      label: initial_fear_worst
                      text: How accurate is this statement: "I fear for the worst."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_frustrated
                      text: How accurate is this statement: "I am not easily frustrated."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_bothered
                      text: How accurate is this statement: "I not easily bothered by things."?
                      answer_type_label: accuracy
                  -
                      label: initial_comfortable_self
                      text: How accurate is this statement: "I feel comfortable with myself."?
                      answer_type_label: accuracy
                  -
                      label: initial_blue
                      text: How accurate is this statement: "I often feel blue."?
                      answer_type_label: accuracy
                  -
                      label: initial_mood_swing
                      text: How accurate is this statement: "I have frequent mood swings."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_blue
                      text: How accurate is this statement: "I seldom feel blue."?
                      answer_type_label: accuracy
                  -
                      label: initial_calm_pressure
                      text: How accurate is this statement: "I remain calm under pressure."?
                      answer_type_label: accuracy
                  -
                      label: initial_threatened
                      text: How accurate is this statement: "I feel threatened easily."?
                      answer_type_label: accuracy
                  -
                      label: initial_composed
                      text: How accurate is this statement: "I rarely lose my composure."?
                      answer_type_label: accuracy
                  -
                      label: initial_doubts
                      text: How accurate is this statement: "I am filled with doubts about things."?
                      answer_type_label: accuracy
        -
              label: initial_openess
              questions:
                  -
                      label: initial_not_poetry
                      text: How accurate is this statement: "I do not like poetry."?
                      answer_type_label: accuracy
                  -
                      label: initial_imagination
                      text: How accurate is this statement: "I have a vivid imagination."?
                      answer_type_label: accuracy
                  -
                      label: initial_vocab
                      text: How accurate is this statement: "I have a rich vocabulary."?
                      answer_type_label: accuracy
                  -
                      label: initial_new_ideas
                      text: How accurate is this statement: "I enjoy hearing new ideas."?
                      answer_type_label: accuracy
                  -
                      label: initial_conservative
                      text: How accurate is this statement: "I tend to vote for conservative political candidates."?
                      answer_type_label: accuracy  
                  -
                      label: initial_not_philosophical
                      text: How accurate is this statement: "I avoid philosophical discussions."?
                      answer_type_label: accuracy  
                  -
                      label: initial_fantasy
                      text: How accurate is this statement: "I tend to day dream."?
                      answer_type_label: accuracy   
                  -
                      label: initial_liberal
                      text: How accurate is this statement: "I tend to vote for liberal political candidates."?
                      answer_type_label: accuracy 
                  -
                      label: initial_not_deep
                      text: How accurate is this statement: "I rarely look for a deeper meaning in things."?
                      answer_type_label: accuracy           
                  -
                      label: initial_new_ideas2
                      text: How accurate is this statement: "I get excited by new ideas."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_support_artists
                      text: How accurate is this statement: "I believe that too much tax money goes to support artists."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_museum
                      text: How accurate is this statement: "I do not enjoy going to art museums."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_art
                      text: How accurate is this statement: "I do not like art."?
                      answer_type_label: accuracy
                  -
                      label: initial_art
                      text: How accurate is this statement: "I believe in the importance of art."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_abstract
                      text: How accurate is this statement: "I am not interested in abstract ideas."?
                      answer_type_label: accuracy
                  -
                      label: initial_higher_conversation
                      text: How accurate is this statement: "I carry the conversation to a higher level."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_theory
                      text: How accurate is this statement: "I am not interested in theoretical discussions."?
                      answer_type_label: accuracy
                  -
                      label: initial_eloquent
                      text: How accurate is this statement: "I can say things beautifully."?
                      answer_type_label: accuracy
                  -
                      label: initial_not_abstract
                      text: How accurate is this statement: "I have difficulty understanding abstract ideas."?
                      answer_type_label: accuracy
                  -
                      label: initial_thinking
                      text: How accurate is this statement: "I enjoy thinking about things."?
                      answer_type_label: accuracy
    questionnaires:
      -
          label: sarcasm_daily
          blocks:
                - sarcasm
                - stress
                - coping_strategies
                - neurotic_tendencies
      -
        label: initial
        blocks:
              - initial_neurotic
              - initial_openess
              - stress
              - coping_strategies
    schedule:
        -
            time_offset_hours: 0
            questionnaire: initial
        -
            time_offset_hours: 2
            questionnaire: sarcasm_daily
        -
            time_offset_hours: 24
            questionnaire: sarcasm_daily
        -
            time_offset_hours: 48
            questionnaire: sarcasm_daily
        -
            time_offset_hours: 72
            questionnaire: sarcasm_daily
        -
            time_offset_hours: 96
            questionnaire: sarcasm_daily
        -
            time_offset_hours: 120
            questionnaire: sarcasm_daily
        -
            time_offset_hours: 144
            questionnaire: sarcasm_daily
        -
            time_offset_hours: 168
            questionnaire: sarcasm_daily
